:default_bank_user:
    :bank:
        :username: "asystest505"
        :password: "pass123$"
        :name: "Angela"

    :strongauth: false

:default_card_user:
    :card:
        :username: "TODO"
        :password: "TODO"

    :strongauth: "TODO"

:default_sso_user:
    :bank:
        :username: "asysssocred4"
        :password: "pass123$"
        :name: "A"

    :card:
        :username: "asysssocred4"
        :password: "pass123$"
        :name: "LN227052855"

    :strongauth: true

:securityAnswer: "test"
:afternoon_hour: 12
:evening_hour: 18