:login:
    :bank:
        :username: "asystest506"
        :password: "pass123$"
        :name: "Charmayne"
    :card:
        :username: "TODO"
        :password: "TODO"
        :name: "TODO"
:securityAnswer: "test"